/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#76755",
        "primary-container": "#2e4b57",
        "on-error-container": "#ff9993",
        "on-error": "#490106",
        "secondary-fixed": "#ffddb4",
        "on-tertiary-fixed-variant": "#55656d",
        "primary-fixed-dim": "#bbd9e9",
        "surface-container-low": "#131313",
        "secondary-dim": "#d29129",
        "secondary-fixed-dim": "#ffcc88",
        "on-primary-container": "#b7d5e5",
        "error": "#ee7d77",
        "error-dim": "#bb5551",
        "on-tertiary-fixed": "#394951",
        "secondary": "#d29129",
        "error-container": "#7f2927",
        "surface-container-high": "#1f2020",
        "on-secondary-fixed": "#593800",
        "surface-tint": "#adcbda",
        "on-secondary-container": "#f9b148",
        "surface-container": "#191a1a",
        "inverse-primary": "#466370",
        "on-background": "#e7e5e4",
        "surface": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "on-primary-fixed-variant": "#435f6d",
        "inverse-on-surface": "#565555",
        "on-secondary": "#301c00",
        "tertiary-fixed": "#dff1fb",
        "tertiary-fixed-dim": "#d1e2ec",
        "surface-container-highest": "#252626",
        "surface-variant": "#252626",
        "tertiary": "#f4faff",
        "on-primary-fixed": "#264350",
        "primary": "#adcbda",
        "background": "#0e0e0e",
        "on-surface": "#e7e5e4",
        "surface-bright": "#2c2c2c",
        "secondary-container": "#543500",
        "on-tertiary-container": "#495961",
        "on-secondary-fixed-variant": "#7f5200",
        "inverse-surface": "#fcf9f8",
        "surface-dim": "#0e0e0e",
        "outline-variant": "#484848",
        "on-tertiary": "#51616a",
        "primary-dim": "#9fbdcc",
        "tertiary-dim": "#d1e2ec",
        "primary-fixed": "#c9e7f7",
        "tertiary-container": "#dceef8",
        "on-primary": "#274451",
        "on-surface-variant": "#acabaa"
      },
      fontFamily: {
        "headline": ["Syne", "sans-serif"],
        "body": ["Outfit", "sans-serif"],
        "label": ["Syne", "sans-serif"]
      },
      letterSpacing: {
        "tightest": "-0.06em"
      },
    },
  },
  plugins: [],
}
